name: flutter_web_app
description: flutter_web_app
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  meta: ^1.17.0

flutter:
  uses-material-design: true
