name: flutter_web_app
description: flutter_web_app
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  intl_utils: 2.8.14
  build_runner: 2.13.0

flutter_intl:
  enabled: true

dependency_overrides:
  intl_utils: 2.8.14
  meta: 1.17.0

flutter:
  uses-material-design: true
